language: node_js
dist: trusty
sudo: true
node_js:
- 7.5.0
addons:
  apt:
    packages:
    - python-pip
notifications:
  email: false
  slack:
    rooms:
    - gapminder:siB4Z9ymsYR6qHnRPpgUoB2Q#vizabi-spam
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@latest
- sudo pip install s3cmd
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm run build
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sh deploy.sh || true'
after_success: ".cicd/beta_npm_ver.js"
deploy:
  skip_cleanup: true
  provider: npm
  email: kgrpwnz@gmail.com
  api_key:
    secure: Nwdu0KQzk6fXJuHRGO6Sj7a4/TjYuVuxXBMHHas/Gcf4fdS26TLloAGoPbN2tfb/e2w8Xyv0VOVQIX4ZAA9FRRefgcXkMikoF9GFc4PwH5bnbxdvN8IIPJeAakTtjxcGl3dgMxiZZIL1uzxUT++juqxYBQiqO7AJiTiVWIsoRiw6nPH+n0CRP1o869e5NC/7vHwVPT0LWrG5kFPxEnjAkMEfZUI+ZLJVnjkCQoctsT0Ri/87stI2lLRGLScqn1DBK+f6aRgCGHFsvdCS4tb08PaNufosb4q1o1R8R/jtBU0yYXKGFEzuG5FNtou/tJh1K4jK4vUmf/2cE1WgGNCwZuIQKUn4bJmCQit53DenhhNPRKT8pVuJhrRSpX3N+ZlKer/qkhgId+Dnkb3RcoTTb/Z+5Za2aRKwUnc4/uymuRTDGVzH+MIgsP1ws9ui08lDwKHBsoBpHc5rdaM3e+IPA+QvBW1g12HsDTWnTmJSvjoyUzbC9BhvVhemniR23sHjLZxDGHY8yVaZNn63cmUA03fbe+ryChdVB6z3HqDu54Ko54Q9q4U7Y9PAn/snldcPSrYG/s2EouY71L9ADQGNEbSxNFQaPloSRTTCUcrnSpX5nqnlzk+c37hi0DIM9RPtoV8ESFjR8NLechOzlkdjoaJpdlVZ8kHA9Yrac9L83wA=
  on:
    branch: develop
    node: 7.5.0
    condition: "-e /tmp/deployment.flag"
